## 00. Pytorch Fundamental

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [2]:
## Introduction to Tensor

In [3]:
#scaler

scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
vector = torch.tensor([2,3])
vector

tensor([2, 3])

In [6]:
#Matrix
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX.ndim

2

In [7]:
MATRIX.shape

torch.Size([2, 2])

In [8]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [9]:
TENSOR.shape

torch.Size([1, 3, 3])

In [10]:
random_tensor = torch.rand(1,3,4)
random_tensor, random_tensor.dtype, random_tensor.ndim

(tensor([[[0.6339, 0.8737, 0.8056, 0.0918],
          [0.5690, 0.9651, 0.0590, 0.1257],
          [0.0622, 0.0389, 0.0889, 0.7057]]]),
 torch.float32,
 3)

In [11]:
random_image_size_tensor = torch.rand(224, 224, 3)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Range

In [12]:
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
#creating tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)

In [14]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

In [15]:
float_32_tensor = torch.tensor([3.0,6.0, 9.0],
                               dtype=None,
                               device='cpu',
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [16]:
float_32_tensor.dtype

torch.float32

In [17]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [18]:
## Getting Information from tensors


In [19]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4272, 0.8628, 0.9604, 0.9007],
        [0.0018, 0.1255, 0.3838, 0.2747],
        [0.1078, 0.4306, 0.8206, 0.3467]])

In [20]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.4272, 0.8628, 0.9604, 0.9007],
        [0.0018, 0.1255, 0.3838, 0.2747],
        [0.1078, 0.4306, 0.8206, 0.3467]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


# Manipulating tensors (tensor operations)
1. Addition
2. Substraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [21]:
tensor = torch.tensor([1,2,3])
tensor + 10


tensor([11, 12, 13])

In [22]:
torch.add(tensor,100)

tensor([101, 102, 103])

In [23]:
torch.mul(tensor,100)

tensor([100, 200, 300])

#matrix multiplication
1. Element wise
2. matrix multiplication

In [24]:
torch.matmul(tensor,tensor)

tensor(14)

In [25]:
#matrix Multiplciatio by hand

tensor @ tensor

tensor(14)

In [26]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.8097, 0.3422, 0.6911],
        [0.4441, 0.1988, 0.4946],
        [0.8333, 0.3546, 0.7367]])

In [27]:
#shape for matrix multiplication

tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

#mm is eqaul to matlmul
torch.mm(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [28]:
# Findign the min, max, mean, sum etc (tensor aggregarion)

#create a tensor

x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [29]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [30]:
x.dtype

torch.int64

In [31]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [32]:
x.argmin()

tensor(0)

## Reshaping, stacking sqeezing and unsqeezing

In [33]:
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [34]:
# ad extra dimesion
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [35]:
# ad extra dimesion
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [36]:
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [37]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [38]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [39]:
x_squeeze = x_reshaped.squeeze()
x_squeeze

tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]])

In [40]:
x_rand = torch.rand(1,9)
x_rand

tensor([[0.7265, 0.6871, 0.7304, 0.8063, 0.6194, 0.9355, 0.2120, 0.8084, 0.4886]])

In [41]:
x_rand.shape

torch.Size([1, 9])

In [42]:
x_squeeze = x_rand.squeeze()
x_squeeze, x_squeeze.shape

(tensor([0.7265, 0.6871, 0.7304, 0.8063, 0.6194, 0.9355, 0.2120, 0.8084, 0.4886]),
 torch.Size([9]))

In [43]:
x_orignal = torch.rand(size=(224,224,3))
x_permuted = x_orignal.permute(2, 0, 1)


x_orignal.shape,x_permuted.shape



(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing

In [44]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [45]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [46]:
x[0][0]

tensor([1, 2, 3])

In [47]:
x[0][0][0]

tensor(1)

In [48]:
x[0][1][2]

tensor(6)

In [49]:
x[:,0]

tensor([[1, 2, 3]])

In [50]:
x[:,2]

tensor([[7, 8, 9]])

In [51]:
x[:,:,2]

tensor([[3, 6, 9]])

In [52]:
x[:,2,2]

tensor([9])

In [53]:
# Numpy array to ttensor

import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## Reproduciabilty

In [54]:
torch.rand(3,3)

tensor([[0.6960, 0.5065, 0.2658],
        [0.7041, 0.9400, 0.6409],
        [0.2378, 0.4880, 0.1495]])

In [55]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.7895, 0.0189, 0.7422, 0.1563],
        [0.2530, 0.3055, 0.4834, 0.1375],
        [0.7080, 0.9053, 0.7612, 0.6515]])

Tensor B:
tensor([[0.7575, 0.6937, 0.7276, 0.6002],
        [0.2635, 0.8399, 0.4433, 0.9036],
        [0.0319, 0.6937, 0.1233, 0.5889]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [58]:
# Create two random tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# GPU accesing

In [59]:
import psutil
total_ram = psutil.virtual_memory().total / (1024**3)
print("Total RAM:", total_ram, "GB")

Total RAM: 12.674789428710938 GB


In [1]:
!nvidia-smi

Sat May  4 04:11:34 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   68C    P8              13W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [1]:
import torch
torch.cuda.is_available()

True

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
torch.cuda.device_count()

1

# Putting tensor on GPU

In [7]:
tensor = torch.tensor([1,2,3])
# tensor on cpu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [8]:
tensor_on_gpu = tensor.to(device)
# tensor on cpu
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [9]:
# Moving tensors sback to cpu
# if tensor is on cpu on GPU, cant transform
tensor_back_on_cpu = tensor_on_gpu.cpu()
tensor_back_on_cpu

tensor([1, 2, 3])

In [ ]:
# Exercise & Extra Curriculum