# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch
x = torch.rand(7,7)
x

# Create random tensor


tensor([[0.5744, 0.8112, 0.0850, 0.7449, 0.3143, 0.3210, 0.1424],
        [0.4386, 0.4740, 0.8892, 0.6085, 0.1535, 0.4607, 0.6065],
        [0.5519, 0.5992, 0.9487, 0.7920, 0.9349, 0.6324, 0.6550],
        [0.3318, 0.9424, 0.3386, 0.3983, 0.7931, 0.4897, 0.1377],
        [0.8768, 0.9685, 0.5792, 0.1624, 0.7840, 0.4106, 0.7515],
        [0.3344, 0.9601, 0.0237, 0.7977, 0.9356, 0.9992, 0.2272],
        [0.8136, 0.6389, 0.4605, 0.5815, 0.0506, 0.1387, 0.6187]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [9]:
# Create another random tensor
a = torch.rand(1,7).T
torch.mm(x,a)

# Perform matrix multiplication


tensor([[1.5447],
        [1.3550],
        [1.8610],
        [1.6487],
        [2.1346],
        [1.9718],
        [1.5379]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
x = torch.rand(7,7)
# Matrix multiply tensors
a = torch.rand(1,7).T
torch.mm(x,a)



tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [2]:
# Set random seed on the GPU
import torch
torch.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)
x=torch.rand(2,3)
y=torch.rand(2,3)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
x1=torch.rand(2,3, device="cuda")
y1=torch.rand(2,3, device="cuda")


In [6]:
x1

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [8]:
# Perform matmul on tensor_A and tensor_B
torch.mm(x1, y1.T)


tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [11]:
# Find max
print(torch.mm(x1, y1.T).max())
# Find min
print(torch.mm(x1, y1.T).min())


tensor(0.7668, device='cuda:0')
tensor(0.2786, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [12]:
# Find arg max
print(torch.mm(x1, y1.T).argmax())
# Find arg min
print(torch.mm(x1, y1.T).argmin())

tensor(1, device='cuda:0')
tensor(0, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [14]:
# Set seed
torch.manual_seed(7)

# Create random tensor
a1 = torch.rand(1,1,1,10)

# Remove single dimensions
a2=a1.squeeze()

# Print out tensors and their shapes
a1, a2, a1.shape, a2.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([1, 1, 1, 10]),
 torch.Size([10]))